// All prompts sourced from the official Wavelength app.
// As with everything about this project, all credit obviously goes to the original creators!

export const prompts = [
    // Starter Pack (1-24)
    { id: 1, left: "Bad movie", right: "Good movie" },
    { id: 2, left: "Bad person", right: "Good person" },
    { id: 3, left: "Culturally significant", right: "Culturally insignificant" },
    { id: 4, left: "Dry food", right: "Wet food" },
    { id: 5, left: "Easy to do", right: "Hard to do" },
    { id: 6, left: "Feels bad", right: "Feels good" },
    { id: 7, left: "Hairless", right: "Hairy" },
    { id: 8, left: "Hard to remember", right: "Easy to remember" },
    { id: 9, left: "Hot", right: "Cold" },
    { id: 10, left: "Inflexible", right: "Flexible" },
    { id: 11, left: "Messy food", right: "Clean food" },
    { id: 12, left: "Need", right: "Want" },
    { id: 13, left: "Normal thing to own", right: "Weird thing to own" },
    { id: 14, left: "Poorly made", right: "Well made" },
    { id: 15, left: "Quiet place", right: "Loud place" },
    { id: 16, left: "Rare", right: "Common" },
    { id: 17, left: "Role model", right: "Bad influence" },
    { id: 18, left: "Round animal", right: "Pointy animal" },
    { id: 19, left: "Soft", right: "Hard" },
    { id: 20, left: "Ugly", right: "Beautiful" },
    { id: 21, left: "Underpaid", right: "Overpaid"},
    { id: 22, left: "Underrated skill", right: "Overrated skill"},
    { id: 23, left: "Useless", right: "Useful"},
    { id: 24, left: "Villain", right: "Hero"},

    // Jumbo Pack (25-174)
    { id: 25, left: "Weak", right: "Strong" },
    { id: 26, left: "80s thing", right: "90s thing" },
    { id: 27, left: "Action movie", right: "Adventure movie" },
    { id: 28, left: "Artisanal", right: "Mass produced" },
    { id: 29, left: "Bad", right: "Good" },
    { id: 30, left: "Bad actor", right: "Good actor" },
    { id: 31, left: "Bad for you", right: "Good for you" },
    { id: 32, left: "Bad gift", right: "Good gift" },
    { id: 33, left: "Bad habit", right: "Good habit" },
    { id: 34, left: "Bad man", right: "Good man" },
    { id: 35, left: "Bad music", right: "Good music" },
    { id: 36, left: "Bad pizza topping", right: "Good pizza topping" },
    { id: 37, left: "Bad superpower", right: "Good superpower" },
    { id: 38, left: "Bad TV", right: "Good TV" },
    { id: 39, left: "Basic", right: "Hipster" },
    { id: 40, left: "Better hot", right: "Better cold" },
    { id: 41, left: "Book was better", right: "Movie was better" },
    { id: 42, left: "Boring", right: "Exciting" },
    { id: 43, left: "Boring topic", right: "Fascinating topic" },
    { id: 44, left: "Casual", right: "Formal" },
    { id: 45, left: "Cat person", right: "Dog person" },
    { id: 46, left: "Cheap", right: "Expensive" },
    { id: 47, left: "Colorless", right: "Colorful" },
    { id: 48, left: "Comedy", right: "Drama" },
    { id: 49, left: "Dangerous", right: "Safe" },
    { id: 50, left: "Dangerous job", right: "Safe job" },
    { id: 51, left: "Dark", right: "Light" },
    { id: 52, left: "Difficult to use", right: "Easy to use" },
    { id: 53, left: "Dirty", right: "Clean" },
    { id: 54, left: "Disgusting cereal", right: "Delicious cereal" },
    { id: 55, left: "Divided", right: "Whole" },
    { id: 56, left: "Doesn't vape", right: "Vapes" },
    { id: 57, left: "Dog name", right: "Cat name" },
    { id: 58, left: "Dry", right: "Wet" },
    { id: 59, left: "Dystopia", right: "Utopia" },
    { id: 60, left: "Easy subject", right: "Hard subject" },
    { id: 61, left: "Easy to kill", right: "Hard to kill" },
    { id: 62, left: "Easy to spell", right: "Hard to spell" },
    { id: 63, left: "Ethical to eat", right: "Unethical to eat" },
    { id: 64, left: "Fad", right: "Classic" },
    { id: 65, left: "Failure", right: "Masterpiece" },
    { id: 66, left: "Famous", right: "Infamous" },
    { id: 67, left: "Fantasy", right: "Sci-Fi" },
    { id: 68, left: "Flavorless", right: "Flavorful" },
    { id: 69, left: "For kids", right: "For adults" },
    { id: 70, left: "Forbidden", right: "Encouraged" },
    { id: 71, left: "Fragile", right: "Durable" },
    { id: 72, left: "Freedom fighter", right: "Terrorist" },
    { id: 73, left: "Friend", right: "Enemy" },
    { id: 74, left: "Geek", right: "Dork" },
    { id: 75, left: "Good", right: "Evil" },
    { id: 76, left: "Gryffindor", right: "Slytherin" },
    { id: 77, left: "Guilty pleasure", right: "Openly love" },
    { id: 78, left: "Happens slowly", right: "Happens suddenly" },
    { id: 79, left: "Hard to find", right: "Easy to find" },
    { id: 80, left: "Hard to pronounce", right: "Easy to pronounce" },
    { id: 81, left: "Harmless", right: "Harmful" },
    { id: 82, left: "Has a bad reputation", right: "Has a good reputation" },
    { id: 83, left: "Historically important", right: "Historically irrelevant" },
    { id: 84, left: "Ineffective", right: "Effective" },
    { id: 85, left: "Inessential", right: "Essential" },
    { id: 86, left: "Introvert", right: "Extrovert" },
    { id: 87, left: "Least evil company", right: "Most evil company" },
    { id: 88, left: "Liberal", right: "Conservative" },
    { id: 89, left: "Limp", right: "Firm" },
    { id: 90, left: "Looks like a person", right: "Doesn't look like a person" },
    { id: 91, left: "Loved", right: "Hated" },
    { id: 92, left: "Low calorie", right: "High calorie" },
    { id: 93, left: "Low quality", right: "High quality" },
    { id: 94, left: "Lowbrow", right: "Highbrow" },
    { id: 95, left: "Mainstream", right: "Niche" },
    { id: 96, left: "Mature person", right: "Immature person" },
    { id: 97, left: "Mean person", right: "Nice person" },
    { id: 98, left: "Mental activity", right: "Physical activity" },
    { id: 99, left: "Mildly addictive", right: "Highly addictive" },
    { id: 100, left: "Movie", right: "Film" },
    { id: 101, left: "Movies that Godzilla would ruin", right: "Movies that Godzilla would improve" },
    { id: 102, left: "Nerd", right: "Jock" },
    { id: 103, left: "Nobody does it", right: "Everybody does it" },
    { id: 104, left: "Normal", right: "Weird" },
    { id: 105, left: "Normal pet", right: "Exotic pet" },
    { id: 106, left: "Not a sandwich", right: "A sandwich" },
    { id: 107, left: "Not art", right: "Art" },
    { id: 108, left: "Optional", right: "Mandatory" },
    { id: 109, left: "Ordinary", right: "Extraordinary" },
    { id: 110, left: "Peaceful", right: "Warlike" },
    { id: 111, left: "Plain", right: "Fancy" },
    { id: 112, left: "Proof that God exists", right: "Proof that God doesn't exist" },
    { id: 113, left: "Replaceable", right: "Irreplaceable" },
    { id: 114, left: "Required luck", right: "Requires skill" },
    { id: 115, left: "Rough", right: "Smooth" },
    { id: 116, left: "Round", right: "Pointy" },
    { id: 117, left: "Sad movie", right: "Happy movie" },
    { id: 118, left: "Sad song", right: "Happy song" },
    { id: 119, left: "Scary animal", right: "Nice animal" },
    { id: 120, left: "Short lived", right: "Long lived" },
    { id: 121, left: "Smells bad", right: "Smells good" },
    { id: 122, left: "Smelly in a bad way", right: "Smelly in a good way" },
    { id: 123, left: "Snack", right: "Meal" },
    { id: 124, left: "Sport", right: "Game" },
    { id: 125, left: "Square", right: "Round" },
    { id: 126, left: "Star Wars", right: "Star Trek" },
    { id: 127, left: "Straight", right: "Curvy" },
    { id: 128, left: "Stupid", right: "Brilliant" },
    { id: 129, left: "Sustenance", right: "Haute cuisine" },
    { id: 130, left: "Tasted bad", right: "Tasted good" },
    { id: 131, left: "Temporary", right: "Permanent" },
    { id: 132, left: "The Light Side of the Force", right: "The Dark Side of the Force" },
    { id: 133, left: "Tired", right: "Wired" },
    { id: 134, left: "Traditionally masculine", right: "Traditionally feminine" },
    { id: 135, left: "Trashy", right: "Classy" },
    { id: 136, left: "Ugly man", right: "Beautiful man" },
    { id: 137, left: "Ugly word", right: "Beautiful word" },
    { id: 138, left: "Unbelievable", right: "Believable" },
    { id: 139, left: "Uncontroversial topic", right: "Controversial topic" },
    { id: 140, left: "Uncool", right: "Cool" },
    { id: 141, left: "Underrated", right: "Overrated" },
    { id: 142, left: "Underrated actor", right: "Overrated actor" },
    { id: 143, left: "Underrated letter of the alphabet", right: "Overrated letter of the alphabet" },
    { id: 144, left: "Underrated movie", right: "Overrated movie" },
    { id: 145, left: "Underrated musician", right: "Overrated musician" },
    { id: 146, left: "Underrated thing to do", right: "Overrated thing to do" },
    { id: 147, left: "Underrated thing to own", right: "Overrated thing to do" },
    { id: 148, left: "Underrated weapon", right: "Overrated weapon" },
    { id: 149, left: "Unethical", right: "Ethical" },
    { id: 150, left: "Unfashionable", right: "Fashionable" },
    { id: 151, left: "Unforgivable", right: "Forgivable" },
    { id: 152, left: "Unhealthy", right: "Healthy" },
    { id: 153, left: "Unhygienic", right: "Hygienic" },
    { id: 154, left: "Unimportant", right: "Important" },
    { id: 155, left: "Unknown", right: "Famous" },
    { id: 156, left: "Unnatural", right: "Natural" },
    { id: 157, left: "Unpopular", right: "Popular" },
    { id: 158, left: "Unpopular activity", right: "Popular activity" },
    { id: 159, left: "Unreliable", right: "Reliable" },
    { id: 160, left: "Unsexy animal", right: "Sexy animal" },
    { id: 161, left: "Unsexy Pokémon", right: "Sexy Pokémon" },
    { id: 162, left: "Unstable", right: "Stable" },
    { id: 163, left: "Untalented", right: "Talented" },
    { id: 164, left: "Useless body part", right: "Useful body part" },
    { id: 165, left: "Useless in an emergency", right: "Useful in an emergency" },
    { id: 166, left: "Useless invention", right: "Useful invention" },
    { id: 167, left: "Useless major", right: "Useful major" },
    { id: 168, left: "Vice", right: "Virtue" },
    { id: 169, left: "Waste of time", right: "Good use of time" },
    { id: 170, left: "Wise", right: "Intelligent" },
    { id: 171, left: "Worst athlete of all time", right: "Greatest athlete of all time" },
    { id: 172, left: "Worst day of the year", right: "Best day of the year" },
    { id: 173, left: "Worst living person", right: "Greatest living person" },
    { id: 174, left: "Worthless", right: "Priceless" },
];

export function getRandomPrompt() {
    return prompts[Math.floor(Math.random() * prompts.length)];
}

export function getPromptById(id) {
    return prompts.find(p => p.id === id);
}