export const prompts = [
    { id: 1, left: "Underrated", right: "Overrated" },
    { id: 2, left: "Evil", right: "Good" },
    { id: 3, left: "Cursed", right: "Blessed" },
    { id: 4, left: "Rough", right: "Smooth" },
    { id: 5, left: "Easy", right: "Hard" },
    { id: 6, left: "Inefficient", right: "Efficient" },
    { id: 7, left: "Asymmetrical", right: "Symmetrical" },
    { id: 8, left: "Abstract", right: "Concrete" },
    { id: 9, left: "Sad", right: "Happy" },
    { id: 10, left: "Violent", right: "Peaceful" },
    { id: 11, left: "Mundane", right: "Magical" },
    { id: 12, left: "Ordinary", right: "Exotic" },
    { id: 13, left: "Barbaric", right: "Civilized" },
    { id: 14, left: "Fragile", right: "Sturdy" },
    { id: 15, left: "Sparse", right: "Dense" },
    { id: 16, left: "Wet", right: "Dry" },
    { id: 17, left: "Small", right: "Large" },
    { id: 18, left: "Short", right: "Long" },
    { id: 19, left: "Light", right: "Heavy" },
    { id: 20, left: "Dull", right: "Sharp" },
    { id: 21, left: "Fuzzy", right: "Prickly" },
    { id: 22, left: "Soft", right: "Hard" },
    { id: 23, left: "Dark", right: "Light" },
    { id: 24, left: "Hot", right: "Cold" },
    { id: 25, left: "Quiet", right: "Loud" },
    { id: 26, left: "Transparent", right: "Opaque" },
    { id: 27, left: "Subtle", right: "Obvious" },
    { id: 28, left: "Deep", right: "Shallow" },
    { id: 29, left: "Discrete", right: "Continuous" },
    { id: 30, left: "Weak", right: "Powerful" },
    { id: 31, left: "Bad Smelling", right: "Good Smelling" },
    { id: 32, left: "Ugly", right: "Beautiful" },
    { id: 33, left: "Useless", right: "Useful" },
    { id: 34, left: "Worst Day", right: "Best Day" },
    { id: 35, left: "Cruel", right: "Kind" },
    { id: 36, left: "Hated", right: "Loved" },
    { id: 37, left: "Chaotic", right: "Organized" },
    { id: 38, left: "Slow", right: "Fast" },
    { id: 39, left: "Least Likely to Succeed", right: "Most Likely to Succeed" },
    { id: 40, left: "Needs Improvement", right: "Already Perfect" },
    { id: 41, left: "Looks Bad", right: "Looks Good" },
    { id: 42, left: "Boring", right: "Exciting" },
    { id: 43, left: "Annoying", right: "Pleasing" },
    { id: 44, left: "Naughty", right: "Nice" },
    { id: 45, left: "Guilty", right: "Innocent" },
    { id: 46, left: "Cowardly", right: "Brave" },
    { id: 47, left: "Weak-Willed", right: "Strong-Willed" },
    { id: 48, left: "Lazy", right: "Hard-Working" },
    { id: 49, left: "Dumb", right: "Smart" },
    { id: 50, left: "Sour", right: "Sweet" },
    { id: 51, left: "Spicy", right: "Mild" },
    { id: 52, left: "Tasteless", right: "Tasty" },
    { id: 53, left: "Doesn't Go With Beer", right: "Goes With Beer" },
    { id: 54, left: "Doesn't Go With Wine", right: "Goes With Wine" },
    { id: 55, left: "1-Star Restaurant", right: "5-Star Restaurant" },
    { id: 56, left: "Kitchen Disaster", right: "Michelin Star Chef" },
    { id: 57, left: "Casual Attire", right: "Formal Attire" },
    { id: 58, left: "Unfashionable", right: "Fashionable" },
    { id: 59, left: "Cheap", right: "Expensive" },
    { id: 60, left: "Low Tech", right: "High Tech" },
    { id: 61, left: "Obscure", right: "Mainstream" },
    { id: 62, left: "Uncool", right: "Cool" },
    { id: 63, left: "Lowbrow", right: "Highbrow" },
    { id: 64, left: "Worst Super Power", right: "Best Super Power" },
    { id: 65, left: "Worst Place to Take a Date", right: "Best Place to Take a Date" },
    { id: 66, left: "Not Spooky", right: "Spooky" },
    { id: 67, left: "Unpopular Opinion", right: "Popular Opinion" },
    { id: 68, left: "Under-Seasoned", right: "Over-Seasoned" },
    { id: 69, left: "Inedible", right: "Edible" },
    { id: 70, left: "Looks Fake", right: "Looks Real" },
    { id: 71, left: "Un-Manly", right: "Manly" },
    { id: 72, left: "Nerdy", right: "Sporty" },
    { id: 73, left: "Un-Funny", right: "Funny" },
    { id: 74, left: "Awkward Gift to Receive", right: "Great Gift to Receive" },
    { id: 75, left: "Indefensible", right: "Defensible" },
    { id: 76, left: "Complicated", right: "Simple" },
    { id: 77, left: "Specific", right: "Vague" },
    { id: 78, left: "Low Pressure", right: "High Pressure" },
    { id: 79, left: "Sad Story", right: "Happy Story" },
    { id: 80, left: "Looks Unhealthy", right: "Looks Healthy" }
];

export function getRandomPrompt() {
    return prompts[Math.floor(Math.random() * prompts.length)];
}

export function getPromptById(id) {
    return prompts.find(p => p.id === id);
}